### ISSUE TITLE
易有云插件无法通过luci界面停止

### ISSUE THREAD

**Issue by qingtian110** [linkease/nas-packages-luci#1]
luci-app-linkease 插件，即使关闭 “启用”  并应用，插件依然在运行

**Comment by qingtian110** [comment]
[![](https://s6.jpg.cm/2021/12/07/LQydQ8.png)](http://https://s6.jpg.cm/2021/12/07/LQydQ8.png)

**Comment by jjm2473** [comment]
openwrt和luci分别是什么版本

**Comment by qingtian110** [comment]
> 

openwrt 和 luci 都是官方源码 openwrt-21.02 分支（具体它是什么版本号我不清楚，因为它只显示 luci | git-21.340.48972-61cc3b1）。固件是三天内编译的，易有云插件源码也是最新的。


反正openwrt 源码是这样获取并编译的

git clone https://github.com/openwrt/openwrt -b openwrt-21.02

**Comment by qingtian110** [comment]
我遇到的问题是：通过openwrt 后台，易有云文件管理器 插件关闭程序。程序依然运行（并且正常工作）

我彻底关闭它我目前只能使用   ```/etc/init.d/linkease stop``` 方式

**Comment by jjm2473** [comment]
已解决
