### ISSUE TITLE
quickstart插件页面出现与设备无关的名称字段“ARS2”

### ISSUE THREAD

**Issue by ziguayungui** [linkease/nas-packages-luci#2]
![8fb5f54c3e08b47a3c321dfec0f01a6](https://user-images.githubusercontent.com/7206387/156878174-1fe4af08-4824-45de-b431-5c8c3bdee838.png)

在x86设备上添加了quick-start插件，在旁路由配置页面出现截图中信息“由ARS2来实现一些高级功能”。但是我的设备类型不是ARS2，猜测是代码中 ARS2 为固定字段，未通过获取设备名称或类型 及时替换。

**Comment by jjm2473** [comment]
收到。
quickstart目前是开发给ars2使用的，暂未在其他平台测试过，功能上可能有兼容性问题。

**Comment by jannson** [comment]
这个问题还没修复，尴尬。

下个版本修复吧。老是忘记修改，现在已经支持 X86 的版本了。
