### ISSUE TITLE
quickstart插件页面内容空白

### ISSUE THREAD

**Issue by sleel** [linkease/nas-packages-luci#39]
1.自编译集成了istore和quickstart，istore正常使用，quickstart页面好多显示空白，如软件源配置错误，没有设备连接，磁盘信息也都是空白，最下面的系统信息也不太准确。请问quickstart这些页面正确显示 都需要什么依赖呢？
2.quickstart页面显示内容可以定制吗，比如不显示docker什么的。

**Comment by sleel** [comment]
已解决依赖问题  不过quickstart有个bug  在删除dockerd后 quickstart 的docker页面消失后，磁盘信息也会消失

**Comment by myannnascar** [comment]
> 

方便分享一下需要的基础依赖吗

**Comment by jjm2473** [comment]
docker应该已经是动态显示的了，磁盘信息一般需要依赖lsblk，blkid，等
