### ISSUE TITLE
首页可以更改成别的网口吗

### ISSUE THREAD

**Issue by zaishi0103** [linkease/nas-packages-luci#49]
![Screenshot_2022-11-20-16-50-51-453_com android chrome](https://user-images.githubusercontent.com/34189712/202893724-e20108da-303e-4fb8-b35a-0fa6ebcaea4b.jpg)
一直显示iptv不显示wan

**Comment by zaishi0103** [comment]
iptv是单线复用的iptv口。显示的网口是按照拼音排序的吧，能不能改长，像首页网口那样选择哪个口子显示流量。

**Comment by jjm2473** [comment]
首页显示的是默认网关（路由表 0.0.0.0 的那个）所在的接口的IP，难道iptv还需要默认网关？

**Comment by zaishi0103** [comment]
就是多wan

**Comment by ZiGmaX809** [comment]
同样的问题，IPTV内网融合就会导致显示IPTV的地址和流量，如果把接口改成wan2之类的又显示的正常wan口的数据。

附图：
![img](https://raw.githubusercontent.com/ZiGmaX809/ZiGmaX809.github.io/7b3ff296688f0b25f2742619ba086d70f3ad44f2/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20230710102121.png)

**Comment by ZiGmaX809** [comment]
> “状态”-“路由表” 截图看看现在的路由信息

同样的问题，IPTV内网融合就会导致显示IPTV的地址和流量，如果把接口改成wan2之类的又显示的正常wan口的数据。

附图：
![img](https://raw.githubusercontent.com/ZiGmaX809/ZiGmaX809.github.io/7b3ff296688f0b25f2742619ba086d70f3ad44f2/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20230710102121.png)

**Comment by jjm2473** [comment]
不要把iptv设置成默认网关就行了，谁tm用iptv作为默认网关
