### ISSUE TITLE
>

### ISSUE THREAD

**Issue by sleel** [linkease/nas-packages-luci#50]
> 

方便分享一下需要的基础依赖吗

_Originally posted by @myannnascar in https://github.com/linkease/nas-packages-luci/issues/39#issuecomment-1367456066_
      
这就看你要装什么插件了   我需求很小  加个bash  ttyd就基本正常了  前提是按说明拉取源   如果不用docker的话   一定要添加docker的config 否则磁盘信息空白

**Comment by jjm2473** [comment]
没事开新issue干嘛
