### ISSUE TITLE
istorex  对 raid 支持不友好

### ISSUE THREAD

**Issue by zctmdc** [linkease/nas-packages-luci#54]
[Powered by LuCI istoreos-21.02 branch (git-22.332.46448-a322196)](https://github.com/openwrt/luci) / [ArgonTheme v2.2.9.4](https://github.com/jerrykuku/luci-theme-argon) / iStoreOS 21.02.3 2022121613
```
istorex  v0.5.5.0
```

我有几块放了较久的sata 500g 硬盘，我将其放在一个古老的机器上用来体验 `iStoreOS` 但是我发现了一些问题：

1. 快速开始页面一直提示 手动挂载 raid `/cgi-bin/luci/admin/quickstart/` 
 
    ![image](https://user-images.githubusercontent.com/24244480/215259895-f40fc014-f376-412a-9cd7-b8c6cffaa7cf.png)
    ![image](https://user-images.githubusercontent.com/24244480/215259930-ae1f1e7a-1811-4791-b4a5-914cdab394f7.png)

2. istorex 页面提示raid 未挂载
    ![image](https://user-images.githubusercontent.com/24244480/215259966-12b2db85-58bc-4ac9-849a-70b281e4a178.png)
3. istorex 中 ns套件 无法识别已经挂载 的raid信息
    ![image](https://user-images.githubusercontent.com/24244480/215260044-3e00a061-850f-47b0-9e7a-d6cc050b9bc7.png)

我使用的是 系统 > 磁盘管理 > 重新进行的分区 信息如下
![image](https://user-images.githubusercontent.com/24244480/215260087-4249ea2d-b64a-4057-880e-5b3e2088c731.png)
通过系统 > 挂载点进行的挂载 信息如下
![image](https://user-images.githubusercontent.com/24244480/215260121-ce94772a-5de8-44c5-981a-bc982c3e712a.png)

ssh 中磁盘信息如下

![image](https://user-images.githubusercontent.com/24244480/215260153-f4b36753-6236-4054-9fd1-4fb06164e35d.png)

**Comment by jjm2473** [comment]
可能istorex那边默认raid是不分区的

**Comment by jjm2473** [comment]
修复了，等下个版本固件，如果自己编译固件的话更新feed即可。目前istorex的向导那边还是没显示raid分区，需要等作者更新

**Comment by zctmdc** [comment]
谢谢您的支持

**Comment by zctmdc** [comment]
谢谢您的支持
