### ISSUE TITLE
最新的大雕源码编译 首页不显示磁盘信息，之前配置了docker配置文件可以显示，这次不显示了

### ISSUE THREAD

**Issue by feifan1113** [linkease/nas-packages-luci#55]
求大佬帮解决
<img width="636" alt="image" src="https://user-images.githubusercontent.com/57245399/215915839-953d85f8-86ed-4396-b321-a59a8d6e4be6.png">

**Comment by feifan1113** [comment]
重启quickstart
出现这提示
Wed Feb  1 08:36:08 2023 daemon.err uhttpd[4227]: sh: /etc/init.d/tasks: line 7: extra_command: not found
Wed Feb  1 08:36:08 2023 daemon.err uhttpd[4227]: sh: /etc/init.d/tasks: line 8: extra_command: not found
Wed Feb  1 08:36:08 2023 daemon.err uhttpd[4227]: sh: /etc/init.d/tasks: line 9: extra_command: not found
Wed Feb  1 08:36:08 2023 daemon.err uhttpd[4227]: sh: /etc/init.d/tasks: line 10: extra_command: not found
Wed Feb  1 08:36:08 2023 daemon.err uhttpd[4227]: sh: /etc/init.d/tasks: line 11: extra_command: not found
Wed Feb  1 08:36:20 2023 daemon.err uhttpd[4227]: sh: /etc/init.d/tasks: line 7: extra_command: not found
Wed Feb  1 08:36:20 2023 daemon.err uhttpd[4227]: sh: /etc/init.d/tasks: line 8: extra_command: not found
Wed Feb  1 08:36:20 2023 daemon.err uhttpd[4227]: sh: /etc/init.d/tasks: line 9: extra_command: not found
Wed Feb  1 08:36:20 2023 daemon.err uhttpd[4227]: sh: /etc/init.d/tasks: line 10: extra_command: not found
Wed Feb  1 08:36:20 2023 daemon.err uhttpd[4227]: sh: /etc/init.d/tasks: line 11: extra_command: not found

**Comment by jjm2473** [comment]
`Wed Feb 1 08:36:08 2023 daemon.err uhttpd[4227]: sh: /etc/init.d/tasks: line 7: extra_command: not found`错误是istore或者istorex产生的，跟quickstart无关。这个错误是由于openwrt版本太低，没有extra_command函数，可以提议lede那边增加这个函数，我也看看能不能兼容。

至于quickstart的问题，打开浏览器的网络调试，刷新页面，看看有没有报错。

**Comment by jjm2473** [comment]
不对啊，如果不支持extra_command，那他们的dockerd肯定会报错 https://github.com/coolsnowwolf/packages/blob/master/utils/dockerd/files/dockerd.init

**Comment by jjm2473** [comment]
而且lede老早就支持extra_command了 https://github.com/coolsnowwolf/lede/commit/22cfbe7faa2e9d32e5c78b273d05cee806861c12

**Comment by jjm2473** [comment]
extra_command的错误应该不用管，还是回到quickstart吧

**Comment by feifan1113** [comment]
> `Wed Feb 1 08:36:08 2023 daemon.err uhttpd[4227]: sh: /etc/init.d/tasks: line 7: extra_command: not found`错误是istore或者istorex产生的，跟quickstart无关。~这个错误是由于openwrt版本太低，没有extra_command函数，可以提议lede那边增加这个函数，我也看看能不能兼容。~
> 
> 至于quickstart的问题，打开浏览器的网络调试，刷新页面，看看有没有报错。

只有samba ddns wedav的报错，因为我没搞这些
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/57245399/215926312-02987bd4-d407-4399-a94b-18d0f26ba085.png"><img width="552" alt="image" src="https://user-images.githubusercontent.com/57245399/215926475-107f2c80-053e-4f75-9474-61d675d6eab9.png">

**Comment by jjm2473** [comment]
打开“Network”标签页

**Comment by feifan1113** [comment]
> 

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/57245399/215928705-34f578bc-e1db-4ede-9b42-6a4eaaeebd2a.png">
看不出有磁盘信息xi相关报错 我之前pve下用都是可以显示的，这次编译居然不显示了

**Comment by feifan1113** [comment]
https://tcysl-my.sharepoint.com/:u:/g/personal/od2_tcysl_onmicrosoft_com/EQHkEdrmzypHvnsKMWLXMHoBhbfre_AnbCy6bmud0Nz0Jw?e=Fy2gVX


大佬 这是我的op镜像 192.268.2.3  密码 password 可以帮看看是什么原因的，如果需要带efi的 我一会上传

**Comment by jjm2473** [comment]
我是说浏览器调试面板的“Network”，不是页面上的网络

**Comment by jjm2473** [comment]
我用你的镜像看看吧

**Comment by feifan1113** [comment]
> 我用你的镜像看看吧

大佬，试得如何了？

**Comment by jjm2473** [comment]
@feifan1113  修好了，更新feed。
磁盘和docker都能显示了。

不过你的固件里面的uHTTPd有其他问题，浏览器并发请求数量多的话就会有部分请求失败，产生这个错误：
```
Unable to launch the requested CGI program:
  /www/cgi-bin/luci: No such file or directory

```

**Comment by feifan1113** [comment]
> 

感谢大佬🙏，uHTTPd这个问题指的是某插件还是指多个插件还是说是整个系统的？是源码兼容性问题吗

**Comment by feifan1113** [comment]
另外针对首页，我有几个建议：
1，最新版本的qucikstart流量统计显示数据出来的时间好像比之前的久了
2，流量统计那个卡片界面太大了 可以适当调小点
3，系统信息可以调到磁盘信息那里，磁盘信息在右边
4，建议加入dhcp列表信息，直观的知道哪些设备的ip，可以设置在系统信息那个卡片的位置，就是下图的dhpcp分配，最好包含v6的
<img width="981" alt="image" src="https://user-images.githubusercontent.com/57245399/216033196-b418794f-5a87-402c-b3f9-d4547dd72c3c.png">
<img width="995" alt="image" src="https://user-images.githubusercontent.com/57245399/216033230-a903aa7c-b4fe-49e0-a6ec-65b550718251.png">

**Comment by jjm2473** [comment]
> 感谢大佬🙏，uHTTPd这个问题指的是某插件还是指多个插件还是说是整个系统的？是源码兼容性问题吗
跟插件无关，只是quickstart的首页打开时并发请求比较多，这个uHTTPd就会出错，出错的请求单独执行却没问题，其他固件完全没遇到这个问题。

**Comment by jjm2473** [comment]
UI的调整要跟设计师沟通，中间的模块可能以后还会增删，不太可能固定成你说的样子。

**Comment by feifan1113** [comment]
> UI的调整要跟设计师沟通，中间的模块可能以后还会增删，不太可能固定成你说的样子。

也是，可以弄个在系统那弄个首页设置选项，用于选择开启关闭部分卡片，另外建议在流量统计或者已连接设备的子项加入wrtbwmon这个插件，可以显示各个设备实时流量
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/57245399/216039157-b0a2b639-e3fc-4cf2-92d3-7166fbbcc690.png">

**Comment by feifan1113** [comment]
> > 感谢大佬🙏，uHTTPd这个问题指的是某插件还是指多个插件还是说是整个系统的？是源码兼容性问题吗
> 
> 跟插件无关，只是quickstart的首页打开时并发请求比较多，这个uHTTPd就会出错，出错的请求单独执行却没问题，其他固件完全没遇到这个问题。

可能因为我那固件首页很多子项功能缺失导致的请求失败较多
