### ISSUE TITLE
vm-tools和zerotier有冲突

### ISSUE THREAD

**Issue by petererong** [linkease/nas-packages-luci#58]
zerotier是iStore安装的luci-app-zerotier
vm-tools是软件包opkg的open-vm-tools

具体问题是，两者都安装的情况下，重启后zerotier不能自动连接，zerotier-cli info显示OFFLINE，在路由器界面里先取消启用zerotier，应用，再勾选启用zerotier，应用，才能连接

卸载open-vm-tools之后，zerotier恢复正常，重启后可以自动连接

**Comment by jjm2473** [comment]
两个应该没啥关系，zerotier卸载重装试试，应该已经修复了
