### ISSUE TITLE
quickstart 网页上无法获取磁盘信息和docker信息

### ISSUE THREAD

**Issue by ufk119** [linkease/nas-packages-luci#6]
自编译5.15内核，使用quickstart无法获取磁盘信息以及docker状态
![1](https://user-images.githubusercontent.com/55911453/164366562-3f8b4ea6-4a24-4d2b-85ac-3eac730dd4c4.png)
。

**Comment by jannson** [comment]
可能有不兼容的问题，到时候用你的固件我们定位下。你的固件在哪里？

**Comment by ufk119** [comment]
> 可能有不兼容的问题，到时候用你的固件我们定位下。你的固件在哪里？
> 
> 还有刚刚修复了一些兼容问题，特别是 磁盘的，请确认下最新的版本

最近没看github，后续版本已修复，谢谢回复。
