### ISSUE TITLE
istoreosX网络向导界面打不开

### ISSUE THREAD

**Issue by duilehaojiu** [linkease/nas-packages-luci#60]
![image](https://user-images.githubusercontent.com/114590024/227762694-368dcdd1-6fb2-4d59-92e3-e885b2705c1c.png)

**Comment by Carseason** [comment]
是不是在非istoreos上使用quickstar?

**Comment by duilehaojiu** [comment]
> 是不是在非istoreos上使用quickstar?

是第三方编译的openwrt，有办法让他能用或者或者把他删掉吗

**Comment by duilehaojiu** [comment]
> opkg remove luci-app-istorex

是我没表达清除，我的意思是有办法让这个quickstart界面显示出来或者单独将quickstart这个选项从右边栏里删除吗

**Comment by jjm2473** [comment]
网络向导是quickstart的功能，你怎么会跳转到这？

**Comment by jjm2473** [comment]
你编译的固件是openwrt 21版本以上吗，有没有加上 luci-compat 依赖？

**Comment by duilehaojiu** [comment]
刚才重新编译了一份固件，然后从istore里安装的istoreX，莫名其妙的好了，网络向导也可以显示了
