### ISSUE TITLE
关于首页ui优化显示ip超出边界的问题

### ISSUE THREAD

**Issue by MAOGE2018** [linkease/nas-packages-luci#61]
http://192.168.100.1/cgi-bin/luci/admin/istorex/router/index

如截图。地球下面的ip已经换行了，建议修改成不换行的，更好看点。
![微信截图_20230404111657](https://user-images.githubusercontent.com/39059232/229678175-2d3adfa4-3069-45b6-8bd6-810e555bcfdc.png)
------------------------
主机名 | iStoreOS
-- | --
型号 | Default string Default string
架构 | Intel(R) Pentium(R) Gold 8505
目标平台 | x86/64
固件版本 | iStoreOS 21.02.3 2023033111 / LuCI istoreos-21.02 branch git-23.088.34636-f8cc111
内核版本 | 5.4.188
本地时间 | 2023-04-04 11:18:46
运行时间 | 1h 56m 11s
平均负载 | 0.11, 0.21, 0.25

**Comment by jjm2473** [comment]
需要 @Carseason  看看
