### ISSUE TITLE
IPTV内网融合后，Quickstart页面只显示IPTV信息

### ISSUE THREAD

**Issue by ZiGmaX809** [linkease/nas-packages-luci#67]
IPTV内网融合就会导致显示IPTV的地址和流量，如果把接口改成wan2之类的又显示的正常wan口的数据。

F12看了一下发现Quickstart server返回的数据就不对，所以可能需要修改上游文件，无法本地解决。

麻烦修改一下增加一个wan口的判断，谢谢。

附 路由表 图：
![img](https://raw.githubusercontent.com/ZiGmaX809/ZiGmaX809.github.io/7b3ff296688f0b25f2742619ba086d70f3ad44f2/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20230710102121.png)

_Originally posted by @ZiGmaX809 in https://github.com/linkease/nas-packages-luci/issues/49#issuecomment-1628012809_

**Comment by jjm2473** [comment]
怎么还在发这个，去discussions里面搜一下，是因为你把iptv接口设置成默认网关了！

**Comment by ZiGmaX809** [comment]
牛逼  

openwrt这个翻译有问题啊，应该翻译成

作为默认网关

而不是

使用默认网关
