### ISSUE TITLE
[bug]易有云文件管理器，上传文件跨域问题

### ISSUE THREAD

**Issue by fankangsong** [linkease/nas-packages-luci#68]
复现场景：

istoreos 的管理端访问地址端口非 80、443，例如：https://xxx.com:4431 ，使用易有云上传文件会有跨域上传失败的问题。

**Comment by jjm2473** [comment]
易有云跟istoreos的管理界面有啥关系？

**Comment by fankangsong** [comment]
> 易有云跟istoreos的管理界面有啥关系？

主要是跨域问题，这个可以复现，把 istroeos 的管理入口 192.160.100.1:80 端口，改成 192.168.100.1:8080 ，易有云就无法上传文件了。问题应该是易有云文件管理器调用异步接口，写死了端口号。

**Comment by jjm2473** [comment]
ref https://github.com/istoreos/istoreos/issues/1159

**Comment by ks-bao** [comment]
收到！下周解决
