### ISSUE TITLE
编译失败，更新和luci-base冲突

### ISSUE THREAD

**Issue by ywt114** [linkease/nas-packages-luci#70]
* check_data_file_clashes: Package luci-app-istorex wants to install file /home/runner/work/test/test/openwrt/build_dir/target-x86_64_musl/root-x86/www/index.html
	But that file is already provided by package  * luci-base
 * opkg_install_cmd: Cannot install package luci-app-istorex.
make[2]: *** [package/Makefile:70: package/install] Error 255
make[1]: *** [package/Makefile:111: /home/runner/work/test/test/openwrt/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[2]: Leaving directory '/home/runner/work/test/test/openwrt'
make[1]: Leaving directory '/home/runner/work/test/test/openwrt'
make: *** [/home/runner/work/test/test/openwrt/include/toplevel.mk:231: world] Error 2
Error: Process completed with exit code 2.

**Comment by ywt114** [comment]
是3天前luci-app-istorex的更新后出现的路径冲突，使用lean的源

**Comment by jjm2473** [comment]
代码结构是有问题的，等修复吧

**Comment by ywt114** [comment]
> 代码结构是有问题的，等修复吧

你指的是这边linkease的修复，还是lean那边源的修复？

**Comment by jjm2473** [comment]
等luci-app-istorex修复

**Comment by ywt114** [comment]
> 等luci-app-istorex修复

已测试 已修复 非常感谢 再请教个问题 第三方openwrt安装istorex后 在登录界面后跳转默认是/cgi-bin/luci/admin/quickstart 如何修改让他自动跳转至/cgi-bin/luci/admin/istorex
