### ISSUE TITLE
默认跳转路径调整

### ISSUE THREAD

**Issue by ywt114** [linkease/nas-packages-luci#71]
请教个问题 第三方openwrt安装istorex后 在登录界面后跳转默认是/cgi-bin/luci/admin/quickstart 如何修改让他自动跳转至/cgi-bin/luci/admin/istorex

**Comment by jjm2473** [comment]
参考这个补丁 https://github.com/jjm2473/luci/commit/37c783a03d21f17451ac08ade3fe108fda7139ab
