### ISSUE TITLE
quickstart & istorex does not support JavaScript source minification

### ISSUE THREAD

**Issue by xuexijiaoben** [linkease/nas-packages-luci#76]
luci-app-quickstart does not support JavaScript source minification
luci-app-istorex does not support JavaScript source minification
固件也能编译完，但是过程中提示上述两个错误，
请问这个有什么具体的影响么？

**Comment by jjm2473** [comment]
没，就是因为openwrt sdk里面的js压缩工具有bug，所以这两个插件都禁止js压缩了。
